name: Publish @deriv-com/smartcharts-champion
on:
    workflow_dispatch:

jobs:
    build_and_publish_smart_charts:
        runs-on: Ubuntu-latest
        env:
          HUSKY: 0  # Disable Husky hooks
        permissions:
            contents: write
        steps:
            - name: Checkout smartcharts-champion
              uses: 'deriv-com/smartcharts-champion/.github/actions/checkout@master'
              with:
                  repository: 'deriv-com/smartcharts-champion'
                  path: smartcharts-champion
                  ref: master

            - name: Custom flutter-chart
              id: flutter_chart
              uses: 'deriv-com/smartcharts-champion/.github/actions/checkout@master'
              with:
                  repository: 'deriv-com/flutter-chart'
                  path: flutter-chart
                  ref: master
            - uses: subosito/flutter-action@62f096cacda5168a3bd7b95793373be14fa4fbaf
              with:
                  flutter-version: '3.24.1'
                  channel: 'stable'
                  cache: true
            - name: Build flutter
              run: |
                  cd smartcharts-champion/chart_app
                  flutter pub get
                  flutter build web --web-renderer html --release

            - name: Setup node
              uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
              with:
                  node-version: 22.x

            - name: Setup smartcharts-champion
              run: cd smartcharts-champion && npm install

            - name: Build smartcharts-champion
              run: cd smartcharts-champion && npm run build
            - name: Release smartcharts-champion
              env:
                  CI: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: cd smartcharts-champion && npx semantic-release
